/**
 * 视觉主题四预设（web/cc/pi/opencode）：每个预设持 dark/light 两版
 * 「变量 + 语义角色」色板，/theme 与 /preset 切换。
 *
 * 取值来源：
 * - web：dsh web 设计 token（palette.ts，原默认）；
 * - pi：earendil-works/pi 官方 dark.json/light.json 逐字取值
 *   （packages/coding-agent/src/modes/interactive/theme/*.json）；
 * - opencode：OpenCode 默认主题 opencode.json 逐字取值
 *   （packages/tui/src/theme/assets/opencode.json，defs 展开）；
 * - cc：Claude Code 终端视觉特征的自研诠释（暖橙 accent、无边框灰阶、
 *   GitHub 系语法色）——非官方取值，注释里已声明。
 * @module dsh-tui-app/app/pi/theme-presets
 */

import type { PaletteSet } from './palette.ts'
import { ansiPaletteSet } from './palette.ts'
import { WEB_PALETTE } from './palette.ts'

export type ThemePresetId = 'web' | 'cc' | 'pi' | 'opencode' | 'ansi'

/* ============ cc（Claude Code 风格诠释） ============ */

/** cc dark：暖橙 accent（Claude terracotta）、近无边框灰阶、GitHub Dark 语法色。 */
const CC_DARK_VARS: Record<string, string> = {
  cyan: '#58A6FF',
  sky: '#58A6FF',
  blue: '#484F58',
  green: '#3FB950',
  red: '#F85149',
  yellow: '#D29922',
  violet: '#BC8CFF',
  text: '#ECECEC',
  gray: '#8B8E93',
  dimGray: '#5C5F64',
  darkGray: '#30333A',
  accent: '#D97757',
  selectedBg: '#2A2E36',
  userMsgBg: '#1F2227',
  toolPendingBg: '#20242B',
  toolSuccessBg: '#152B1E',
  toolErrorBg: '#3B1B1B',
  customMsgBg: '#262236',
}
const CC_DARK_COLORS: Record<string, string> = {
  accent: 'accent',
  info: 'sky',
  border: '#30333A',
  borderAccent: '#484F58',
  borderMuted: '#21242A',
  success: 'green',
  error: 'red',
  warning: 'yellow',
  muted: 'gray',
  dim: 'dimGray',
  text: 'text',
  thinkingText: 'dimGray',
  thinkingL1: 'gray',
  thinkingL2: 'dimGray',
  thinkingL3: 'darkGray',
  selectedBg: 'selectedBg',
  scrollbarThumb: 'selectedBg',
  searchMatchBg: 'selectedBg',
  searchMatchText: 'text',
  userMessageBg: 'userMsgBg',
  userMessageText: 'text',
  customMessageBg: 'customMsgBg',
  customMessageText: 'text',
  customMessageLabel: 'violet',
  toolPendingBg: 'toolPendingBg',
  toolSuccessBg: 'toolSuccessBg',
  toolErrorBg: 'toolErrorBg',
  toolTitle: 'text',
  toolOutput: 'gray',
  mdHeading: '#ECECEC',
  mdLink: '#58A6FF',
  mdLinkUrl: 'dimGray',
  mdCode: 'accent',
  mdCodeBlock: '#ECECEC',
  mdCodeBlockBorder: 'darkGray',
  mdQuote: 'gray',
  mdQuoteBorder: 'darkGray',
  mdHr: 'darkGray',
  mdListBullet: 'accent',
  toolDiffAdded: 'green',
  toolDiffRemoved: 'red',
  toolDiffContext: 'gray',
  syntaxComment: '#8B949E',
  syntaxKeyword: '#FF7B72',
  syntaxFunction: '#D2A8FF',
  syntaxVariable: '#FFA657',
  syntaxString: '#A5D6FF',
  syntaxNumber: '#79C0FF',
  syntaxType: '#FFA657',
  syntaxOperator: '#C9D1D9',
  syntaxPunctuation: '#C9D1D9',
}

const CC_LIGHT_VARS: Record<string, string> = {
  cyan: '#0969DA',
  sky: '#0969DA',
  blue: '#8250DF',
  green: '#1A7F37',
  red: '#CF222E',
  yellow: '#9A6700',
  violet: '#8250DF',
  text: '#1F2328',
  gray: '#57606A',
  dimGray: '#6E7781',
  darkGray: '#D0D7DE',
  accent: '#BF5B32',
  selectedBg: '#F2E2DC',
  userMsgBg: '#F6F8FA',
  toolPendingBg: '#F0F2F4',
  toolSuccessBg: '#E4F4E8',
  toolErrorBg: '#FBE9E9',
  customMsgBg: '#F0EDF7',
}
const CC_LIGHT_COLORS: Record<string, string> = {
  ...CC_DARK_COLORS,
  border: '#D0D7DE',
  borderAccent: '#8C959F',
  borderMuted: '#E4E8EC',
  customMessageLabel: 'violet',
  mdHeading: '#1F2328',
  mdLink: '#0969DA',
  mdCodeBlock: '#1F2328',
  mdCodeBlockBorder: 'darkGray',
  syntaxComment: '#6E7781',
  syntaxKeyword: '#CF222E',
  syntaxFunction: '#8250DF',
  syntaxVariable: '#953800',
  syntaxString: '#0A3069',
  syntaxNumber: '#0550AE',
  syntaxType: '#953800',
  syntaxOperator: '#24292F',
  syntaxPunctuation: '#24292F',
}

/* ============ pi（官方 dark/light.json 逐字） ============ */

const PI_DARK_VARS: Record<string, string> = {
  cyan: '#00d7ff',
  sky: '#5f87ff',
  blue: '#5f87ff',
  green: '#b5bd68',
  red: '#cc6666',
  yellow: '#ffff00',
  violet: '#9575cd',
  text: '#d4d4d4',
  gray: '#808080',
  dimGray: '#666666',
  darkGray: '#505050',
  accent: '#8abeb7',
  selectedBg: '#3a3a4a',
  userMsgBg: '#343541',
  toolPendingBg: '#282832',
  toolSuccessBg: '#283228',
  toolErrorBg: '#3c2828',
  customMsgBg: '#2d2838',
}
const PI_DARK_COLORS: Record<string, string> = {
  accent: 'accent',
  info: 'blue',
  border: 'blue',
  borderAccent: 'cyan',
  borderMuted: 'darkGray',
  success: 'green',
  error: 'red',
  warning: 'yellow',
  muted: 'gray',
  dim: 'dimGray',
  text: 'text',
  thinkingText: 'gray',
  thinkingL1: '#b294bb',
  thinkingL2: '#81a2be',
  thinkingL3: '#6e6e6e',
  selectedBg: 'selectedBg',
  scrollbarThumb: 'selectedBg',
  searchMatchBg: 'selectedBg',
  searchMatchText: 'text',
  userMessageBg: 'userMsgBg',
  userMessageText: 'text',
  customMessageBg: 'customMsgBg',
  customMessageText: 'text',
  customMessageLabel: '#9575cd',
  toolPendingBg: 'toolPendingBg',
  toolSuccessBg: 'toolSuccessBg',
  toolErrorBg: 'toolErrorBg',
  toolTitle: 'text',
  toolOutput: 'gray',
  mdHeading: '#f0c674',
  mdLink: '#81a2be',
  mdLinkUrl: 'dimGray',
  mdCode: 'accent',
  mdCodeBlock: 'green',
  mdCodeBlockBorder: 'gray',
  mdQuote: 'gray',
  mdQuoteBorder: 'gray',
  mdHr: 'gray',
  mdListBullet: 'accent',
  toolDiffAdded: 'green',
  toolDiffRemoved: 'red',
  toolDiffContext: 'gray',
  syntaxComment: '#6A9955',
  syntaxKeyword: '#569CD6',
  syntaxFunction: '#DCDCAA',
  syntaxVariable: '#9CDCFE',
  syntaxString: '#CE9178',
  syntaxNumber: '#B5CEA8',
  syntaxType: '#4EC9B0',
  syntaxOperator: '#D4D4D4',
  syntaxPunctuation: '#D4D4D4',
}

const PI_LIGHT_VARS: Record<string, string> = {
  cyan: '#5a8080',
  sky: '#547da7',
  blue: '#547da7',
  green: '#588458',
  red: '#aa5555',
  yellow: '#9a7326',
  violet: '#7e57c2',
  text: '#1f2328',
  gray: '#6c6c6c',
  dimGray: '#767676',
  darkGray: '#b0b0b0',
  accent: '#5a8080',
  selectedBg: '#d0d0e0',
  userMsgBg: '#e8e8e8',
  toolPendingBg: '#e8e8f0',
  toolSuccessBg: '#e8f0e8',
  toolErrorBg: '#f0e8e8',
  customMsgBg: '#ede7f6',
}
const PI_LIGHT_COLORS: Record<string, string> = {
  ...PI_DARK_COLORS,
  border: 'blue',
  borderAccent: 'accent',
  borderMuted: 'darkGray',
  customMessageLabel: '#7e57c2',
  mdHeading: 'yellow',
  mdLink: 'blue',
  mdCode: 'accent',
  mdCodeBlock: 'green',
  mdCodeBlockBorder: 'gray',
  mdQuote: 'gray',
  mdQuoteBorder: 'gray',
  mdHr: 'gray',
  mdListBullet: 'green',
  syntaxComment: '#008000',
  syntaxKeyword: '#0000FF',
  syntaxFunction: '#795E26',
  syntaxVariable: '#001080',
  syntaxString: '#A31515',
  syntaxNumber: '#098658',
  syntaxType: '#267F99',
  syntaxOperator: '#6c6c6c',
  syntaxPunctuation: '#6c6c6c',
}

/* ============ opencode（默认主题 opencode.json 逐字，defs 展开） ============ */

const OC_DARK_VARS: Record<string, string> = {
  cyan: '#56b6c2',
  sky: '#56b6c2',
  blue: '#5c9cf5',
  green: '#7fd88f',
  red: '#e06c75',
  yellow: '#e5c07b',
  violet: '#9d7cd8',
  text: '#eeeeee',
  gray: '#808080',
  dimGray: '#606060',
  darkGray: '#3c3c3c',
  accent: '#9d7cd8',
  selectedBg: '#1e1e1e',
  userMsgBg: '#141414',
  toolPendingBg: '#141414',
  toolSuccessBg: '#20303b',
  toolErrorBg: '#37222c',
  customMsgBg: '#1e1e1e',
}
const OC_DARK_COLORS: Record<string, string> = {
  accent: 'accent',
  info: 'sky',
  border: '#484848',
  borderAccent: '#606060',
  borderMuted: '#3c3c3c',
  success: 'green',
  error: 'red',
  warning: '#f5a742',
  muted: 'gray',
  dim: 'dimGray',
  text: 'text',
  thinkingText: 'dimGray',
  thinkingL1: 'violet',
  thinkingL2: 'gray',
  thinkingL3: '#484848',
  selectedBg: 'selectedBg',
  scrollbarThumb: 'selectedBg',
  searchMatchBg: 'selectedBg',
  searchMatchText: 'text',
  userMessageBg: 'userMsgBg',
  userMessageText: 'text',
  customMessageBg: 'customMsgBg',
  customMessageText: 'text',
  customMessageLabel: 'violet',
  toolPendingBg: 'toolPendingBg',
  toolSuccessBg: 'toolSuccessBg',
  toolErrorBg: 'toolErrorBg',
  toolTitle: 'text',
  toolOutput: 'gray',
  mdHeading: 'violet',
  mdLink: '#fab283',
  mdLinkUrl: 'dimGray',
  mdCode: 'green',
  mdCodeBlock: 'text',
  mdCodeBlockBorder: '#484848',
  mdQuote: 'yellow',
  mdQuoteBorder: '#484848',
  mdHr: 'gray',
  mdListBullet: '#fab283',
  toolDiffAdded: '#4fd6be',
  toolDiffRemoved: '#c53b53',
  toolDiffContext: '#828bb8',
  syntaxComment: 'gray',
  syntaxKeyword: 'violet',
  syntaxFunction: '#fab283',
  syntaxVariable: 'red',
  syntaxString: 'green',
  syntaxNumber: '#f5a742',
  syntaxType: 'yellow',
  syntaxOperator: 'cyan',
  syntaxPunctuation: '#a0a0a0',
}

const OC_LIGHT_VARS: Record<string, string> = {
  cyan: '#318795',
  sky: '#318795',
  blue: '#3b7dd8',
  green: '#3d9a57',
  red: '#d1383d',
  yellow: '#b0851f',
  violet: '#7b5bb6',
  text: '#1a1a1a',
  gray: '#8a8a8a',
  dimGray: '#a0a0a0',
  darkGray: '#d4d4d4',
  accent: '#d68c27',
  selectedBg: '#ebebeb',
  userMsgBg: '#f5f5f5',
  toolPendingBg: '#fafafa',
  toolSuccessBg: '#d5e5d5',
  toolErrorBg: '#f7d8db',
  customMsgBg: '#f5f5f5',
}
const OC_LIGHT_COLORS: Record<string, string> = {
  ...OC_DARK_COLORS,
  border: '#b8b8b8',
  borderAccent: '#a0a0a0',
  borderMuted: '#d4d4d4',
  warning: 'accent',
  thinkingL1: 'violet',
  thinkingL2: 'gray',
  thinkingL3: '#b8b8b8',
  mdHeading: 'accent',
  mdLink: 'blue',
  mdCode: 'green',
  mdListBullet: 'blue',
  toolDiffAdded: '#1e725c',
  toolDiffContext: '#7086b5',
  syntaxComment: 'gray',
  syntaxKeyword: 'violet',
  syntaxFunction: 'blue',
  syntaxVariable: 'red',
  syntaxString: 'green',
  syntaxNumber: 'accent',
  syntaxType: 'yellow',
  syntaxOperator: 'cyan',
  syntaxPunctuation: 'gray',
}

/* ============ 汇总 ============ */

export interface ThemePreset {
  id: ThemePresetId
  /** /theme 选项里的显示名。 */
  label: string
  dark: PaletteSet
  light: PaletteSet
}

export const THEME_PRESETS: readonly ThemePreset[] = [
  { id: 'web', label: 'web — dsh web 设计 token（默认）', dark: WEB_PALETTE.dark, light: WEB_PALETTE.light },
  { id: 'cc', label: 'cc — Claude Code 风格', dark: { vars: CC_DARK_VARS, colors: CC_DARK_COLORS }, light: { vars: CC_LIGHT_VARS, colors: CC_LIGHT_COLORS } },
  { id: 'pi', label: 'pi — pi coding-agent 官方主题', dark: { vars: PI_DARK_VARS, colors: PI_DARK_COLORS }, light: { vars: PI_LIGHT_VARS, colors: PI_LIGHT_COLORS } },
  { id: 'opencode', label: 'opencode — OpenCode 默认主题', dark: { vars: OC_DARK_VARS, colors: OC_DARK_COLORS }, light: { vars: OC_LIGHT_VARS, colors: OC_LIGHT_COLORS } },
  { id: 'ansi', label: 'ansi — 16 色 ANSI 回退（旧终端）', dark: ansiPaletteSet('dark'), light: ansiPaletteSet('light') },
]

export function isThemePresetId(value: string): value is ThemePresetId {
  return value === 'web' || value === 'cc' || value === 'pi' || value === 'opencode' || value === 'ansi'
}

export function themePresetById(id: ThemePresetId): ThemePreset {
  return THEME_PRESETS.find(preset => preset.id === id) ?? THEME_PRESETS[0]
}
